# Generated by Django 5.2.8 on 2025-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
