# Generated by Django 5.2.8 on 2025-11-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
