# Generated by Django 5.2.8 on 2025-11-20 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.seller'),
        ),
    ]
