# Generated by Django 5.2.8 on 2025-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Normal_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
