# Generated by Django 5.2.8 on 2025-11-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='card_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
