# Generated by Django 5.2.8 on 2025-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_delivery_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
